name: viewer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.8.0
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  equatable: ^2.0.5
  get_it: ^7.2.0
  cached_network_image: ^3.2.1
  connectivity_plus: ^3.0.2
  flutter_widget_from_html: ^0.10.3
  flutter_flavorizr: ^2.2.1
  responsive_framework: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.0
  bloc_test: ^9.1.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
